# Generated by Django 2.2.4 on 2019-09-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '__first__'),
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('total', models.FloatField(default=0.0, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra',
                'verbose_name_plural': 'Comprobantes de Compras',
                'db_table': 'ComprobanteCompra',
            },
        ),
        migrations.CreateModel(
            name='tipo_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(max_length=20, verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Tipo pago Compras',
                'verbose_name_plural': 'Tipos de pagos de Compras',
                'db_table': 'TipoPago',
            },
        ),
        migrations.CreateModel(
            name='detalle_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCompra', models.DateTimeField(auto_now_add=True, verbose_name='FechaCompra')),
                ('numeroloteproducto', models.CharField(max_length=150, null=True, verbose_name='Numero de lote del Producto')),
                ('cantidad', models.PositiveIntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('preciocompra', models.FloatField(default=0.0, verbose_name='Precio Costo')),
                ('precioventa', models.FloatField(default=0.0, verbose_name='Precio Venta')),
                ('fechavencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='subtotal')),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eldetalle', to='compras.Comprobante')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.ubicacion')),
            ],
            options={
                'verbose_name': 'detalle compra',
                'verbose_name_plural': 'detalle de compras',
                'db_table': 'DetalleCompra',
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.tipo_pago'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.Proveedor'),
        ),
    ]
