# Generated by Django 2.2.4 on 2019-08-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_pago',
            options={'verbose_name': 'Tipo pago ventas', 'verbose_name_plural': 'Tipos de pagos ventas'},
        ),
    ]
