# Generated by Django 2.2.4 on 2019-09-17 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 23, 9, 21, 245580), verbose_name='FechaCompra'),
        ),
    ]
