# Generated by Django 2.2.4 on 2019-09-17 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20190916_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 23, 25, 59, 771631), verbose_name='FechaCompra'),
        ),
    ]
