# Generated by Django 2.2.4 on 2019-08-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20190826_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_pago',
            options={'verbose_name': 'Tipo pago Compras', 'verbose_name_plural': 'Tipos de pagos de Compras'},
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.Proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
