# Generated by Django 2.2.4 on 2019-09-18 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20190916_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.date(2019, 9, 18), verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='numeroloteproducto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de lote'),
        ),
    ]
