# Generated by Django 2.2.4 on 2019-09-19 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20190918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.date(2019, 9, 19), verbose_name='Fecha de Compra'),
        ),
    ]
