# Generated by Django 2.2.4 on 2019-09-21 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20190919_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.date(2019, 9, 20), verbose_name='Fecha de Compra'),
        ),
    ]
