# Generated by Django 2.2.4 on 2019-09-26 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20190920_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra'),
        ),
    ]
