# Generated by Django 2.2.4 on 2019-09-26 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_auto_20190925_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='FechaCompra',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra'),
        ),
    ]
