# Generated by Django 2.2.4 on 2019-09-26 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20190925_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha'),
        ),
    ]
