# Generated by Django 2.1.7 on 2019-12-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('perdida', models.FloatField(default=0.0, null=True, verbose_name='Perdidas')),
                ('ganancia', models.FloatField(default=0.0, null=True, verbose_name='Ganancias')),
                ('total', models.FloatField(default=0.0, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'Cajas',
            },
        ),
    ]
