# Generated by Django 2.2.4 on 2019-09-05 05:04

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0009_auto_20190903_1527'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Venta')),
                ('total', models.FloatField(default=0.0, verbose_name='Total')),
                ('efectivo', models.FloatField(default=0.0, null=True, verbose_name='Efectivo')),
                ('vuelto', models.FloatField(default=0.0, null=True, verbose_name='Vuelto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Comprobante de Venta',
                'verbose_name_plural': 'Comprobante de Ventas',
                'db_table': 'ComprobanteVenta',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pago', models.CharField(max_length=30, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.FloatField(default=0, verbose_name='subtotal')),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eldetalle', to='ventas.ComprobanteVenta')),
                ('numlote', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='numeroloteproducto', chained_model_field='numeroloteproducto', on_delete=django.db.models.deletion.CASCADE, to='productos.DetalleProducto')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'db_table': 'DetalleVenta',
            },
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.TipoPago'),
        ),
    ]
