# Generated by Django 2.2.4 on 2019-09-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='numlote',
        ),
    ]
