# Generated by Django 2.2.4 on 2019-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='numeroloteproducto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de lote'),
        ),
    ]
