# Generated by Django 2.2.4 on 2019-09-26 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190925_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Venta'),
        ),
    ]
