# Generated by Django 2.1.7 on 2019-12-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20191025_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='numeroloteproducto',
            field=models.CharField(blank=True, help_text='Asegurese de ingresar el numero de lote proximo a vencer', max_length=20, null=True, verbose_name='Numero de lote'),
        ),
    ]
