# Generated by Django 2.2.4 on 2019-09-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='FechaCompra',
            field=models.DateField(verbose_name='FechaCompra'),
        ),
    ]
