# Generated by Django 2.2.4 on 2019-08-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalle de Productos'},
        ),
    ]
