# Generated by Django 2.2.4 on 2019-08-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190826_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='Ubicacion',
        ),
    ]
