# Generated by Django 2.2.4 on 2019-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190916_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacionproducto',
            field=models.CharField(max_length=150, null=True, verbose_name='Ubicacion del Producto'),
        ),
    ]
