# Generated by Django 2.2.4 on 2019-09-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='numeroloteproducto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Numero de lote del Producto'),
        ),
    ]
