# Generated by Django 2.2.4 on 2019-08-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190826_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='meses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Meses a Vencerse'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='fechavencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='numeroloteproducto',
            field=models.CharField(max_length=150, verbose_name='Numero de lote del Producto'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='preciocompra',
            field=models.FloatField(default=0, verbose_name='Precio Costo'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='precioventa',
            field=models.FloatField(default=0, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elproducto', to='productos.Producto'),
            preserve_default=False,
        ),
    ]
