# Generated by Django 2.2.4 on 2019-08-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190827_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado de Producto'),
        ),
    ]
