# Generated by Django 2.2.4 on 2019-09-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190918_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Porcentaje'),
        ),
    ]
