# Generated by Django 2.2.4 on 2019-08-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190828_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado de Producto'),
        ),
    ]
