# Generated by Django 2.2.4 on 2019-09-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190925_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='numeroloteproducto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de lote del Producto'),
        ),
    ]
