# Generated by Django 2.1.7 on 2019-10-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20190925_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto_Empleado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('productos.detalleproducto',),
        ),
        migrations.CreateModel(
            name='Productos_Empleado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('productos.producto',),
        ),
    ]
