# Generated by Django 2.2.4 on 2019-08-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20190829_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='estado',
        ),
    ]
