# Generated by Django 2.2.4 on 2019-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_detalleproducto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Meses a Vencerse'),
        ),
    ]
