# Generated by Django 2.1.7 on 2019-10-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_detalleproducto_empleado_productos_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
