# Generated by Django 2.2.4 on 2019-09-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20190903_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerolote', models.CharField(max_length=150, verbose_name='Numero de lote del Producto')),
            ],
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='numeroloteproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.NumeroLote'),
        ),
    ]
