# Generated by Django 2.2.4 on 2019-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20190904_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='numeroloteproducto',
            field=models.CharField(max_length=150, verbose_name='Numero de lote del Producto'),
        ),
        migrations.DeleteModel(
            name='NumeroLote',
        ),
    ]
