# Generated by Django 2.1.7 on 2019-10-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20191002_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='estado',
        ),
    ]
