# Generated by Django 2.1.7 on 2019-10-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_detalleproducto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipop', models.CharField(max_length=150, verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'tipoproducto',
                'verbose_name_plural': 'tipoproductos',
                'db_table': 'tipoproducto',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto'),
        ),
    ]
