# Generated by Django 2.1.7 on 2019-10-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20191010_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='tipop',
            new_name='TipoProducto',
        ),
    ]
