# Generated by Django 2.1.7 on 2019-10-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20191010_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipop',
            new_name='tipoProducto',
        ),
    ]
