# Generated by Django 2.1.7 on 2019-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20191220_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='TipoProducto',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tipo de Producto'),
        ),
    ]
