# Generated by Django 2.2.4 on 2019-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='NIT',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='Ingrese NIT'),
        ),
    ]
