# Generated by Django 2.1.7 on 2019-12-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
