# Generated by Django 2.2.4 on 2019-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='comision',
            field=models.FloatField(verbose_name='Comision'),
        ),
    ]
