# Generated by Django 2.2.4 on 2019-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=11, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
    ]
