# Generated by Django 2.2.4 on 2019-08-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
    ]
