# Generated by Django 2.1.7 on 2019-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_auto_20190925_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=11, unique=True, verbose_name='NIT'),
        ),
    ]
